import { TicketInterface } from 'spinal-models-ticket/declarations/SpinalTicket';
export declare class ServiceTicket {
    contextId: string;
    private context;
    private processNames;
    private processes;
    private initialized;
    private steps;
    private tickets;
    private processByStep;
    private stepByProcess;
    private ticketByStep;
    constructor();
    init(): void;
    addDefaultSentence(processId: string, sentence: string): Promise<boolean | string>;
    addStep(stepId: string, processId: string): Promise<boolean | Error>;
    addTicket(ticketId: string, stepId: string): Promise<boolean | Error>;
    createProcess(name: string): Promise<string | Error>;
    createStep(name: string, color: string): string;
    createTicket(info: TicketInterface): any;
    createArchives(): Promise<boolean | Error>;
    getContext(): Promise<string>;
    getAllProcess(): Set<string>;
    getAllTickets(): Set<string>;
    getStepsFromProcess(processId: string): string[];
    getTicketsFromStep(stepId: string): string[];
    private initVar;
    private addStepToProcess;
    private addTicketToStep;
    private createContext;
    private addSentenceSection;
}
