import { TicketInterface } from 'spinal-models-ticket/declarations/SpinalTicket';
import { SpinalProcess } from 'spinal-models-ticket/declarations/SpinalProcess';
import { SpinalLogTicket } from 'spinal-models-ticket/dist/SpinalLogTicket';
export declare class ServiceTicketPersonalized {
    constructor();
    createContext(contextName: string, steps?: Array<any>): Promise<any | Error>;
    getContexts(): any[];
    createProcess(process: SpinalProcess, contextId: string): Promise<string>;
    getAllProcess(contextId: string): Promise<import("spinal-env-viewer-graph-service/declarations/GraphManagerService").SpinalNodeRef[]>;
    addStep(name: string, color: string, order: number, processId: string, contextId: string): Promise<boolean | Error>;
    addStepById(stepId: string, processId: string, contextId: string): Promise<boolean | Error>;
    getStepsFromProcess(processId: string): Promise<any>;
    getFirstStep(processId: string, contextId: string): Promise<string>;
    getNextStep(processId: string, stepId: string): Promise<any>;
    getPreviousStep(processId: string, stepId: string): Promise<any>;
    addTicket(ticketInfo: TicketInterface, processId: string, contextId: string, nodeId: string): Promise<string | Error>;
    getTicketsFromStep(stepId: string): Promise<any>;
    moveTicket(ticketId: string, stepFromId: string, stepToId: string, contextId: string): Promise<void>;
    moveTicketToNextStep(contextId: string, processId: string, ticketId: string): Promise<void>;
    moveTicketToPreviousStep(contextId: string, processId: string, ticketId: string): Promise<void>;
    createLog(info: SpinalLogTicket): string;
    getTicketForUser(userId: string): Promise<any>;
    createArchives(contextId: string): Promise<boolean | Error>;
    addCommonIncident(processId: string, sentence: string): Promise<boolean | string>;
    getCommonIncident(processId: string): Promise<any>;
    private modifyStepProcessId;
    private modifyTicketStepId;
    private createTicket;
    private createStep;
    private getContextSteps;
    private addSentenceSection;
}
